import fs from "node:fs/promises";
import path from "node:path";
import yaml from "yaml";
import { initRepository } from "./init.js";
import { ensureSalaciaDirs } from "./paths.js";
import {
  type AgentProbe,
  type ProjectProbe,
  detectAdapter,
  detectProject,
  probeAllAgents
} from "./auto-detect.js";
import {
  type ProjectMemoryContext,
  writeMemoryFiles
} from "./memory.js";

export interface InstallIssue {
  severity: "error" | "warning" | "info";
  code: string;
  message: string;
  suggestion?: string;
}

export interface InstallResult {
  ok: boolean;
  agents: AgentProbe[];
  project: ProjectProbe;
  adapter: string;
  configPath: string;
  claudeMdPath: string;
  agentsMdPath: string;
  issues: InstallIssue[];
  created: string[];
}

export interface HarnessConfig {
  harness: {
    adapter: string;
    topology: "single" | "multi";
    rollback: boolean;
    verification: {
      commands: string[];
    };
    memory: {
      progressFile: string;
      claudeMd: string;
    };
    oversight: {
      protectedPaths: string[];
      approvalPolicy: string;
    };
  };
}

const DEFAULT_PROTECTED_PATHS = [".env", "secrets/", ".salacia/"];

function projectTypeLabel(type: ProjectProbe["type"]): string {
  const labels: Record<string, string> = {
    node: "Node.js / TypeScript",
    python: "Python",
    go: "Go",
    rust: "Rust",
    java: "Java",
    unknown: "Unknown"
  };
  return labels[type] ?? "Unknown";
}

export async function loadHarnessConfig(root: string): Promise<HarnessConfig | null> {
  const configPath = path.join(root, ".salacia", "config.yaml");
  try {
    const raw = await fs.readFile(configPath, "utf8");
    return yaml.parse(raw) as HarnessConfig;
  } catch {
    return null;
  }
}

export async function runInstall(root: string): Promise<InstallResult> {
  const issues: InstallIssue[] = [];
  const created: string[] = [];

  // Step 1: Init .salacia directories
  const initResult = await initRepository(root);
  created.push(...initResult.created);

  // Step 2: Probe all agents
  const agents = await probeAllAgents();
  const executorAgents = agents.filter((a) => a.kind === "executor" && a.available);
  if (executorAgents.length === 0) {
    issues.push({
      severity: "error",
      code: "no-agent-found",
      message: "No AI coding agent found on this system.",
      suggestion:
        "Install one of: claude (npm i -g @anthropic-ai/claude-code), codex (npm i -g @openai/codex), opencode (npm i -g opencode)"
    });
  }

  // Step 3: Detect project
  const project = await detectProject(root);
  if (project.type === "unknown") {
    issues.push({
      severity: "warning",
      code: "unknown-project",
      message: "Could not detect project type.",
      suggestion: "Salacia will use minimal verification. Add a package.json, pyproject.toml, or go.mod."
    });
  }
  if (project.testCommands.length === 0) {
    issues.push({
      severity: "warning",
      code: "no-test-command",
      message: "No test command detected.",
      suggestion: "Add a test script to your project configuration for full self-verification."
    });
  }
  if (!project.hasGit) {
    issues.push({
      severity: "warning",
      code: "no-git",
      message: "Not inside a git repository.",
      suggestion: "Run `git init` for snapshot/rollback support."
    });
  }

  // Step 4: Auto-detect adapter
  let adapterName = "claude-code";
  try {
    const detection = await detectAdapter();
    adapterName = detection.adapter.name;
  } catch {
    if (executorAgents.length > 0) {
      adapterName = executorAgents[0]!.name;
    }
  }

  // Step 5: Generate config.yaml
  const paths = await ensureSalaciaDirs(root);
  const verificationCommands = [...project.testCommands, ...project.lintCommands];
  const config: HarnessConfig = {
    harness: {
      adapter: adapterName,
      topology: "single",
      rollback: true,
      verification: {
        commands: verificationCommands.length > 0 ? verificationCommands : ["echo 'no verification configured'"]
      },
      memory: {
        progressFile: ".salacia/progress/state.json",
        claudeMd: ".salacia/CLAUDE.md"
      },
      oversight: {
        protectedPaths: [...DEFAULT_PROTECTED_PATHS],
        approvalPolicy: "require-on-high-risk"
      }
    }
  };

  const configPath = path.join(paths.salacia, "config.yaml");
  await fs.writeFile(configPath, `# Auto-generated by salacia install\n${yaml.stringify(config)}`, "utf8");
  created.push(configPath);

  // Step 6: Generate CLAUDE.md and AGENTS.md
  const memCtx: ProjectMemoryContext = {
    projectType: projectTypeLabel(project.type),
    testCommands: project.testCommands,
    lintCommands: project.lintCommands,
    buildCommands: project.buildCommands,
    protectedPaths: DEFAULT_PROTECTED_PATHS
  };
  const { claudeMdPath, agentsMdPath } = await writeMemoryFiles(root, memCtx);
  created.push(claudeMdPath, agentsMdPath);

  const hasErrors = issues.some((i) => i.severity === "error");

  return {
    ok: !hasErrors,
    agents,
    project,
    adapter: adapterName,
    configPath,
    claudeMdPath,
    agentsMdPath,
    issues,
    created
  };
}
